<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class IkepsStatusPenyertaan extends Model
{
    use HasFactory;

    protected $table = 'ikeps_status_penyertaan';

    protected $fillable = [
        'tahun',
        'kod_sekolah',

        'akuatik_zon',
        'akuatik_daerah',
        'akuatik_bahagian',
        'akuatik_negeri',
        'akuatik_kebangsaan',
        'akuatik_antarabangsa',

        'badminton_zon',
        'badminton_daerah',
        'badminton_bahagian',
        'badminton_negeri',
        'badminton_kebangsaan',
        'badminton_antarabangsa',

        'bola_baling_zon',
        'bola_baling_daerah',
        'bola_baling_bahagian',
        'bola_baling_negeri',
        'bola_baling_kebangsaan',
        'bola_baling_antarabangsa',

        'bola_jaring_zon',
        'bola_jaring_daerah',
        'bola_jaring_bahagian',
        'bola_jaring_negeri',
        'bola_jaring_kebangsaan',
        'bola_jaring_antarabangsa',

        'bola_keranjang_zon',
        'bola_keranjang_daerah',
        'bola_keranjang_bahagian',
        'bola_keranjang_negeri',
        'bola_keranjang_kebangsaan',
        'bola_keranjang_antarabangsa',

        'bola_sepak_zon',
        'bola_sepak_daerah',
        'bola_sepak_bahagian',
        'bola_sepak_negeri',
        'bola_sepak_kebangsaan',
        'bola_sepak_antarabangsa',

        'bola_tampar_zon',
        'bola_tampar_daerah',
        'bola_tampar_bahagian',
        'bola_tampar_negeri',
        'bola_tampar_kebangsaan',
        'bola_tampar_antarabangsa',

        'boling_tenpin_zon',
        'boling_tenpin_daerah',
        'boling_tenpin_bahagian',
        'boling_tenpin_negeri',
        'boling_tenpin_kebangsaan',
        'boling_tenpin_antarabangsa',

        'gimnastik_artistik_zon',
        'gimnastik_artistik_daerah',
        'gimnastik_artistik_bahagian',
        'gimnastik_artistik_negeri',
        'gimnastik_artistik_kebangsaan',
        'gimnastik_artistik_antarabangsa',

        'gimnastik_berirama_zon',
        'gimnastik_berirama_daerah',
        'gimnastik_berirama_bahagian',
        'gimnastik_berirama_negeri',
        'gimnastik_berirama_kebangsaan',
        'gimnastik_berirama_antarabangsa',

        'golf_zon',
        'golf_daerah',
        'golf_bahagian',
        'golf_negeri',
        'golf_kebangsaan',
        'golf_antarabangsa',

        'hoki_zon',
        'hoki_daerah',
        'hoki_bahagian',
        'hoki_negeri',
        'hoki_kebangsaan',
        'hoki_antarabangsa',

        'kriket_zon',
        'kriket_daerah',
        'kriket_bahagian',
        'kriket_negeri',
        'kriket_kebangsaan',
        'kriket_antarabangsa',

        'memanah_zon',
        'memanah_daerah',
        'memanah_bahagian',
        'memanah_negeri',
        'memanah_kebangsaan',
        'memanah_antarabangsa',

        'merentas_desa_zon',
        'merentas_desa_daerah',
        'merentas_desa_bahagian',
        'merentas_desa_negeri',
        'merentas_desa_kebangsaan',
        'merentas_desa_antarabangsa',

        'olahraga_zon',
        'olahraga_daerah',
        'olahraga_bahagian',
        'olahraga_negeri',
        'olahraga_kebangsaan',
        'olahraga_antarabangsa',

        'pelayaran_zon',
        'pelayaran_daerah',
        'pelayaran_bahagian',
        'pelayaran_negeri',
        'pelayaran_kebangsaan',
        'pelayaran_antarabangsa',

        'ping_pong_zon',
        'ping_pong_daerah',
        'ping_pong_bahagian',
        'ping_pong_negeri',
        'ping_pong_kebangsaan',
        'ping_pong_antarabangsa',

        'ragbi_zon',
        'ragbi_daerah',
        'ragbi_bahagian',
        'ragbi_negeri',
        'ragbi_kebangsaan',
        'ragbi_antarabangsa',

        'sepak_takraw_zon',
        'sepak_takraw_daerah',
        'sepak_takraw_bahagian',
        'sepak_takraw_negeri',
        'sepak_takraw_kebangsaan',
        'sepak_takraw_antarabangsa',

        'skuasy_zon',
        'skuasy_daerah',
        'skuasy_bahagian',
        'skuasy_negeri',
        'skuasy_kebangsaan',
        'skuasy_antarabangsa',

        'sofbol_zon',
        'sofbol_daerah',
        'sofbol_bahagian',
        'sofbol_negeri',
        'sofbol_kebangsaan',
        'sofbol_antarabangsa',

        'tenis_zon',
        'tenis_daerah',
        'tenis_bahagian',
        'tenis_negeri',
        'tenis_kebangsaan',
        'tenis_antarabangsa',

        'angkat_berat_zon', 
        'angkat_berat_daerah', 
        'angkat_berat_bahagian', 
        'angkat_berat_negeri', 
        'angkat_berat_kebangsaan', 
        'angkat_berat_antarabangsa',

        'ekuestrian_zon', 
        'ekuestrian_daerah', 
        'ekuestrian_bahagian', 
        'ekuestrian_negeri', 
        'ekuestrian_kebangsaan', 
        'ekuestrian_antarabangsa',

        'formula_future_zon', 
        'formula_future_daerah', 
        'formula_future_bahagian', 
        'formula_future_negeri', 
        'formula_future_kebangsaan', 
        'formula_future_antarabangsa',

        'futsal_zon', 
        'futsal_daerah', 
        'futsal_bahagian', 
        'futsal_negeri', 
        'futsal_kebangsaan', 
        'futsal_antarabangsa',

        'kabaddi_zon', 
        'kabaddi_daerah', 
        'kabaddi_bahagian', 
        'kabaddi_negeri', 
        'kabaddi_kebangsaan', 
        'kabaddi_antarabangsa',

        'lawn_bowl_zon', 
        'lawn_bowl_daerah', 
        'lawn_bowl_bahagian', 
        'lawn_bowl_negeri', 
        'lawn_bowl_kebangsaan', 
        'lawn_bowl_antarabangsa',

        'lumba_basikal_zon', 
        'lumba_basikal_daerah', 
        'lumba_basikal_bahagian', 
        'lumba_basikal_negeri', 
        'lumba_basikal_kebangsaan', 
        'lumba_basikal_antarabangsa',

        'menembak_zon', 
        'menembak_daerah', 
        'menembak_bahagian', 
        'menembak_negeri', 
        'menembak_kebangsaan', 
        'menembak_antarabangsa',

        'muay_thai_zon', 
        'muay_thai_daerah', 
        'muay_thai_bahagian', 
        'muay_thai_negeri', 
        'muay_thai_kebangsaan', 
        'muay_thai_antarabangsa',

        'petanque_zon', 
        'petanque_daerah', 
        'petanque_bahagian', 
        'petanque_negeri', 
        'petanque_kebangsaan', 
        'petanque_antarabangsa',

        'silambam_zon', 
        'silambam_daerah', 
        'silambam_bahagian', 
        'silambam_negeri', 
        'silambam_kebangsaan', 
        'silambam_antarabangsa',

        'silat_olahraga_zon', 
        'silat_olahraga_daerah', 
        'silat_olahraga_bahagian', 
        'silat_olahraga_negeri', 
        'silat_olahraga_kebangsaan', 
        'silat_olahraga_antarabangsa',

        'taekwondo_zon', 
        'taekwondo_daerah', 
        'taekwondo_bahagian', 
        'taekwondo_negeri', 
        'taekwondo_kebangsaan', 
        'taekwondo_antarabangsa',

        'tinju_zon', 
        'tinju_daerah', 
        'tinju_bahagian', 
        'tinju_negeri', 
        'tinju_kebangsaan', 
        'tinju_antarabangsa',

        'wushu_zon', 
        'wushu_daerah', 
        'wushu_bahagian', 
        'wushu_negeri', 
        'wushu_kebangsaan', 
        'wushu_antarabangsa',

        'lain_1_butiran', 
        'lain_1_zon', 
        'lain_1_daerah', 
        'lain_1_bahagian', 
        'lain_1_negeri', 
        'lain_1_kebangsaan', 
        'lain_1_antarabangsa',

        'lain_2_butiran', 
        'lain_2_zon', 
        'lain_2_daerah', 
        'lain_2_bahagian', 
        'lain_2_negeri', 
        'lain_2_kebangsaan', 
        'lain_2_antarabangsa',

        'lain_3_butiran', 
        'lain_3_zon', 
        'lain_3_daerah', 
        'lain_3_bahagian', 
        'lain_3_negeri', 
        'lain_3_kebangsaan', 
        'lain_3_antarabangsa',

        'created_by', 
        'updated_by',
    ];

}
